# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
{% if bootnode %}
  config.vm.define "{{ bootnode.name }}" do |bootnode|
      bootnode.vm.box = "centos/7"

      bootnode.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "{{ bootnode.name }}.yml"
      end
  end
{%- endif %}
{% for v in nodes %}
  config.vm.define "{{ v.name }}" do |validator|
      validator.vm.box = "centos/7"

      validator.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "{{ v.name }}.yml"
      end
  end
{% endfor %}
end
