# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "validator" do |validator|
      validator.vm.box = "centos/7"

      validator.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "validator.yml"
      end
  end
end
