# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
{% if bootnode %}
  config.vm.define "{{ bootnode.bootnode_name }}" do |bootnode|
      bootnode.vm.box = "centos/7"

      bootnode.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "{{ bootnode.bootnode_name }}.yml"
      end
  end
{% endif %}
{% for v in validators %}
  config.vm.define "{{ v.validator_name }}" do |validator|
      validator.vm.box = "centos/7"

      validator.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "{{ v.validator_name }}.yml"
      end
  end
{% endfor %}
end
